language: go

go:
  - 1.8.x
  - 1.9.x
  - master


before_install:
  - "go get -v github.com/golang/dep/cmd/dep \
      github.com/onsi/ginkgo/ginkgo \
      golang.org/x/tools/cmd/cover \
      go get github.com/mattn/goveralls"

install:
  - dep ensure --vendor-only -v

script:
  - go test -v -covermode=count -coverprofile=coverage.out
  - goveralls \
    -coverprofile=coverage.out \
    -service=travis-ci \
    -repotoken $COVERALLS_TOKEN
