language: go

go:
  - 1.8.x
  - 1.9.x
  - master


before_install:
  - go get -v github.com/golang/dep/cmd/dep github.com/onsi/ginkgo/ginkgo

install:
  - dep ensure --vendor-only -v

script:
  - ginkgo -v -cover
